version: '3'
services:
  nest-backend:
    build: ./backend
    ports:
      - 3000:3000
    links:
      - mongodb
  react-frontend:
    build: ./frontend
    ports:
      - 3001:5000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
  mongodb:
    image: mongo
    ports:
      - 27017:27017